#DodgeCreeper v1.0.0

#Coordinates of interior corners of the arena relative the the spawning location of the arena.
#Values obtained by the difference of arenalocation-cornerlocation

BArena:
  redcorner-L:
    getX: 8
    getZ: -11
  redcorner-R:
    getX: 42
    getZ: -11
  bluecorner-L:
    getX: 42
    getZ: -86
  bluecorner-R:
    getX: 8
    getZ: -86
  spawnheight: -10
  redspawnoffset: -5
  bluespawnoffset: 5
  
creeper:
  chargedcreeper:
    tick: 30
  basiccreeper:
    tick: 15
item:
  stick:
    knockback: 13
    name: Knockback Stick
    description: A stick made for whacking creepers
block:
  creeperspawn: BEDROCK