#DodgeCreeper v2.0.2

#Coordinates of interior corners of the arena relative the the spawning location of the arena.
#Values obtained by the difference of arenalocation-cornerlocation

BArena:
  redcorner-L:
    getX: 8
    getZ: -11
  redcorner-R:
    getX: 42
    getZ: -11
  bluecorner-L:
    getX: 42
    getZ: -86
  bluecorner-R:
    getX: 8
    getZ: -86
  spawnheight: -10
  
  redspawnoffset: -5
  bluespawnoffset: 5
  
#The value yaw is equivalent to looking at a clock where North is 0 degrees and South is 180 degrees.
  redyaw: 180
  blueyaw: 0
  
#Vertical axis represents the changing coordinate when crossing from one side of the team to the other.
  verticalaxis: Z

  
#The middle line represents the number of blocks from a corner to the middle in respect with the vertical axis of the arena.
  middleline: -40
  middlelineblock: BLACK_CONCRETE
  middlelineinvert: false
creeper:
  chargedcreeper:
    tick: 30
    eggtimer: 400
    amount: 1
    
  basiccreeper:
    tick: 15
    eggtimer: 80
    amount: 1
    
#The formula for calculating the probability of a powerUp spawn is probability + (growth * retrys)
item:
  stick:
    knockback: 13
    name: Knockback Stick
    description: A stick made for whacking creepers
  armor:
    enchant: 5
  egg:
    amount: 5
  powerup:
# timer represents the amount of opportunities to call the probability to spawn. (in ticks)
    timer: 200
# check represents the interval (in ticks) that the game checks whether a player is standing on a powerUp
    check: 5
# Stay represents the duration that a powerUp stays available. (in ticks)
    stay: 140
# Cooldown represents the duration of the powerUp
    cooldown: 200
# probability represents the chance of a powerUp spawning, the value 1 being 100%
    probability: 0.10
# Growth represents the increment of probability for each failed call.
    growth: 0.10  
    
block:
  creeperspawn: BEDROCK